Repository AY2324S1-CS2103T-W09-2/tp, pull requests merged in 2023-10, with the labels that each got.

#15 Update about us for Daniel
  docs/AboutUs.md
  docs/images/Ui.png
  docs/images/dloh2236.png
Labels: type.Documentation, priority.High

#17 Add chew01 info to About Us page
  docs/AboutUs.md
  docs/images/chew01.png
Labels: type.Documentation, priority.High

#18 Add PPP for chew01
  docs/team/chew01.md
Labels: type.Documentation, priority.High

#21 Reformat several parts of UG for markbind render
  docs/UserGuide.md
Labels: type.Documentation, priority.High

#23 Add details about Events Management for User Guide
  docs/UserGuide.md
Labels: type.Documentation, priority.High

#25 Update finance section of the User Guide
  docs/UserGuide.md
Labels: type.Documentation, priority.High

#26 Fix bolding syntax
  docs/UserGuide.md
Labels: type.Documentation, priority.High

#24 Add use cases(UC)11 and UC12 for DG and changes to UC9 & UC10
  docs/DeveloperGuide.md
Labels: type.Documentation, priority.High

#34 Update DG structure and add UC9, UC10, UC13
  docs/DeveloperGuide.md
Labels: type.Documentation, priority.High

#39 Add Finance models, commands and parser and their test cases
  src/main/java/seedu/address/logic/commands/finance/AddCommissionCommand.java
  src/main/java/seedu/address/logic/commands/finance/DeleteFinanceCommand.java
  src/main/java/seedu/address/logic/commands/finance/ListFinanceCommand.java
  src/main/java/seedu/address/logic/parser/finance/AddCommissionParser.java
  src/main/java/seedu/address/logic/parser/finance/DeleteFinanceParser.java
  src/main/java/seedu/address/logic/parser/finance/ListFinanceParser.java
  src/main/java/seedu/address/model/finance/Amount.java
  src/main/java/seedu/address/model/finance/Commission.java
  src/main/java/seedu/address/model/finance/Description.java
  src/test/java/seedu/address/logic/commands/finance/AddCommissionCommandTest.java
  src/test/java/seedu/address/logic/commands/finance/DeleteFinanceCommandTest.java
  src/test/java/seedu/address/logic/commands/finance/ListFinanceCommandTest.java
  src/test/java/seedu/address/logic/parser/finance/AddCommissionParserTest.java
  src/test/java/seedu/address/logic/parser/finance/DeleteFinanceParserTest.java
  src/test/java/seedu/address/logic/parser/finance/ListFinanceParserTest.java
  src/test/java/seedu/address/model/finance/AmountTest.java
  src/test/java/seedu/address/model/finance/CommissionTest.java
  src/test/java/seedu/address/model/finance/DescriptionTest.java
  src/test/java/seedu/address/testutil/CommissionBuilder.java
  src/test/java/seedu/address/testutil/TypicalCommissions.java
Labels: priority.High, type.Epic

#49 Change Person object attributes and constructors, Person Add commands…
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/person/Company.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/TelegramName.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#107 Filter events feature
  .github/workflows/codecov.yml
  docs/diagrams/filterSequenceDiagram.puml
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/events/FilterEventNameCommand.java
  src/main/java/seedu/address/logic/commands/events/FilterEventTimeCommand.java
  src/main/java/seedu/address/logic/commands/events/ListEventCommand.java
  src/main/java/seedu/address/logic/parser/events/EventParser.java
  src/main/java/seedu/address/logic/parser/events/FilterEventNameCommandParser.java
  src/main/java/seedu/address/logic/parser/events/FilterEventTimeCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/EventComparator.java
  src/main/java/seedu/address/model/event/EventNameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/event/EventTimeBeforePredicate.java
  src/main/java/seedu/address/model/event/TimeStart.java
  src/main/java/seedu/address/model/event/UniqueEventList.java
  src/test/java/seedu/address/logic/commands/contact/AddContactCommandTest.java
  src/test/java/seedu/address/logic/commands/events/AddEventCommandTest.java
  src/test/java/seedu/address/logic/commands/finance/AddCommissionCommandTest.java
  src/test/java/seedu/address/logic/parser/events/AddEventCommandParserTest.java
  src/test/java/seedu/address/logic/parser/events/EventParserTest.java
  src/test/java/seedu/address/logic/parser/events/FilterEventNameCommandParserTest.java
  src/test/java/seedu/address/logic/parser/events/FilterEventTimeCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/event/EventComparatorTest.java
  src/test/java/seedu/address/model/event/EventNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/event/EventTimeBeforePredicateTest.java
  src/test/java/seedu/address/testutil/TypicalEvents.java
Labels: priority.High

#119 Update finance section in DG requirements for v1.2
  docs/DeveloperGuide.md
Labels: type.Documentation, priority.High

#123 Add filter functionality to the Finance Tab.
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/finance/FilterClientNameCommand.java
  src/main/java/seedu/address/logic/commands/finance/FilterTimeDueCommand.java
  src/main/java/seedu/address/logic/parser/finance/FilterClientNameCommandParser.java
  src/main/java/seedu/address/logic/parser/finance/FilterTimeDueCommandParser.java
  src/main/java/seedu/address/logic/parser/finance/FinanceParser.java
  src/main/java/seedu/address/model/finance/ClientNameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/finance/TimeDue.java
  src/main/java/seedu/address/model/finance/TimeDueBeforePredicate.java
  src/main/java/seedu/address/ui/FinanceCard.java
  src/main/resources/view/FinanceListCard.fxml
  src/test/java/seedu/address/logic/commands/events/FilterEventNameCommandTest.java
  src/test/java/seedu/address/logic/commands/finance/FilterClientNameCommandTest.java
  src/test/java/seedu/address/logic/commands/finance/FilterTimeDueCommandTest.java
  src/test/java/seedu/address/logic/parser/finance/FilterClientNameCommandParserTest.java
  src/test/java/seedu/address/logic/parser/finance/FilterTimeDueCommandParserTest.java
  src/test/java/seedu/address/model/finance/ClientNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/finance/TimeDueBeforePredicateTest.java
Labels: priority.High, type.Enhancement

#124 Add summary functionality in the Finance tab
  src/main/java/seedu/address/logic/commands/finance/SummaryCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/finance/FinanceParser.java
  src/main/java/seedu/address/logic/parser/finance/SummaryCommandParser.java
  src/main/java/seedu/address/model/FinancesBook.java
  src/main/java/seedu/address/model/finance/ClientNameExactMatchPredicate.java
  src/main/java/seedu/address/model/finance/FinanceSummary.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/MainWindow2.java
  src/test/java/seedu/address/logic/commands/finance/SummaryCommandTest.java
  src/test/java/seedu/address/logic/parser/finance/FinanceParserTest.java
  src/test/java/seedu/address/logic/parser/finance/SummaryCommandParserTest.java
  src/test/java/seedu/address/model/finance/ClientNameExactMatchPredicateTest.java
  src/test/java/seedu/address/model/finance/FinanceSummaryTest.java
Labels: priority.High, type.Enhancement
