Repository AY2324S1-CS2103T-W09-2/tp, pull requests merged in 2023-11, with the labels that each got.

#144 Update UG for Events
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/model/person/Person.java
Labels: type.Documentation, priority.High

#145 Fix command result message bug in finance
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/finance/ListFinanceCommand.java
  src/main/java/seedu/address/model/finance/Finance.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/finance/AddCommissionCommandTest.java
  src/test/java/seedu/address/logic/commands/finance/AddExpenseCommandTest.java
  src/test/java/seedu/address/logic/commands/finance/ListFinanceCommandTest.java
  src/test/java/seedu/address/testutil/CommissionBuilder.java
Labels: priority.Medium, type.Bug

#146 Update finance UG
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/finance/EditFinanceCommand.java
Labels: type.Documentation, priority.High

#227 Fix UG documentation
  docs/UserGuide.md
Labels: type.Documentation

#229 Fix client name bug
  src/main/java/seedu/address/model/finance/Finance.java
  src/main/java/seedu/address/ui/FinanceCard.java
Labels: type.Bug, severity.Low

#235 Fix bug CSS file throws `IllegalArgumentFunctionality` Exception
  src/main/resources/view/DarkTheme.css
  src/test/resources/view/DarkTheme.css
Labels: type.Bug

#233 Fix bug: Wrong message constraint for Phone Number
  src/main/java/seedu/address/model/person/Phone.java
Labels: type.Bug

#231 Fix user guide syntax
  docs/UserGuide.md
Labels: type.Documentation

#234 Fix Bug: Related to Client Checking in Events
  src/main/java/seedu/address/model/event/Event.java
  src/test/java/seedu/address/logic/parser/events/EventParserTest.java
  src/test/java/seedu/address/model/event/EventTest.java
Labels: type.Bug

#243 Update PPP sushiyade.md
  docs/team/sushiyade.md
Labels: type.Documentation
